### ISSUE TITLE
[feat] select everyting on ctrl-A

### ISSUE THREAD

**Issue by kometenstaub** [Fevol/obsidian-translate#21]
I would appreciate if I could select all text with `Ctrl`-`A`. The reason for this is that I often copy text into it and would like to use that hotkey for selecting all the text that's already inside it. 

So that I can `Ctrl`-`A`, `Ctrl`-`V` for inserting the new text.

**Comment by Fevol** [comment]
I was not able to reproduce this; is the issue that `Ctrl-A` does not register at all in the Translation View? If so, I'm not sure what could be going wrong: I'm using standard textarea elements, the only thing that I've changed is that the target language field is read-only

![ctrla](https://user-images.githubusercontent.com/8179397/179628808-cb868739-5e9d-430c-968b-e2a8b4a70951.gif)

**Comment by kometenstaub** [comment]
This may be user error on my side. I‘ll try it again tomorrow and report back.

**Comment by kometenstaub** [comment]
It doesn't work for me because I had a hotkey set to it (`editorCallback` for inserting an admonition). It somehow still steals the event, even when the sidebar pane is focused.

I just removed the hotkey so that it works again. I'm wondering whether this is an Obsidian issue, because the command doesn't show up when the sidebar pane is focused and the hotkey does nothing, but it still isn't let through.

**Comment by Fevol** [comment]
So I found a potential fix for the problem: overriding the hotkey in the view scope, though this feels like a horrendous bodge.
https://github.com/Fevol/obsidian-translate/blob/510fc860f41d2bea1a0e58f2d275e4a8c4145ca1/src/ui/translator-components/ViewPage.svelte#L32-L35

Potential fix:
```
view_scope.register(['Mod'], 'A', (e) => {});
```

Issues:
- Every text editing command that could be overridden by the user should be registered to the view scope, including copying and pasting, moving the cursor, etc.
- Would probably have to make two scopes for both the text areas, instead of the translation view

**Comment by kometenstaub** [comment]
Yes, I wouldn't do that. I raised an issue with Obsidian, let's see what happens.

**Comment by kometenstaub** [comment]
This behaviour is intentional. The hotkeys are global, `editorCallback`s just don't get executed because there's no editor.
