### ISSUE TITLE
[BUG] Fanyi Baidu –

### ISSUE THREAD

**Issue by aishanjiang** [Fevol/obsidian-translate#27]
# User report
**Description:** 

---
# Debugger data (do not alter)
**service_version**: "1.0.0"
**obsidian_version**: "0.15.8"
**mobile**: false

**Comment by Fevol** [comment]
Hello! What issue did you encounter with Fanyi Baidu? Did you get a message like: `Validation failed: Unauthorized user`?

If you'd like, you can add me over on Discord at `@Fevol#9470`, so I can help fix this issue more quickly!

**Comment by Fevol** [comment]
@aishanjiang I've marked this issue as stale for now, but I'll keep it open for now. I'm not sure what the problem was that you've encountered, but I have rewritten parts of the Baidu API handler code, so it's possible that your issue is solved now.

If you're still encountering issues, please do let me know. I do not have access to the service myself, so I cannot verify whether it works properly.
