### ISSUE TITLE
deepl - failed to fetch

### ISSUE THREAD

**Issue by ih8snow** [Fevol/obsidian-translate#3]
Hi, 

just testing the plugin, but when I use my (free) Deepl API key, it says "failed to fetch".
Any idea?

BTW, any chance for the user to determine if he uses the pro API? I guess that is a different API domain.
Thanks!

**Comment by Fevol** [comment]
Sorry for the late response!

I haven't been able to verify the workings of that API yet, so it's most likely a bug on my side. I'll be fixing up the handler ASAP.

As for determining whether the users has the free or paid version, that should be easy enough to implement; I could add a simple dropdown that allows you to select the version manually, or automatically set the correct version when the user validates the settings.

**Comment by Fevol** [comment]
@ih8snow Sorry for the long wait! I was hoping to get the update out the same day, but it turns out that some much-needed changes were required before I felt comfortable releasing an update. DeepL should now be fully supported in [release 1.1.0](https://github.com/Fevol/obsidian-translate/releases/tag/1.1.0).

Let me know if you encounter any problems!
