### ISSUE TITLE
When using the provider's DEEPL API, all line breaks are lost.

### ISSUE THREAD

**Issue by EugeneZaharov** [Fevol/obsidian-translate#36]
**58 sec demonstration:**
https://www.loom.com/share/02d2ec2333564a3aabd91c9a785d392a

**Comment by Fevol** [comment]
Hey, many thanks for the bug report! I really appreciate the video demonstrating the issue.

Tiny word of caution, your API key is partially visible in the video, you may want to take down the video so people don't copy it!

I've been able to reproduce the issue: it seems to only apply to DeepL, so it should be reasonably easy to fix. I'll try to publish the fix later today!

**Comment by EugeneZaharov** [comment]
Thanks for your quick response! 

I'll delete the video as soon as possible. Let me know if there's anything else I can do to help with the fix.

PS Your quick response and attention to detail is really appreciated! :)

**Comment by Fevol** [comment]
Update: apparently I had set `split_sentences` for DeepL to `false`, setting it to `true` fixes the issue ([code](https://github.com/Fevol/obsidian-translate/blob/aabf6e8e4b4f48660aabf94510ef2f8a15f20b71/src/handlers/deepl.ts#L91)). For a future release, I'll try to add a toggle for both this setting, and the other features that the DeepL API offers (e.g. formality, preserving formatting, XML tag handling for html, etc.)

**Comment by EugeneZaharov** [comment]
It works, thanks a lot :)

**Comment by Erikk87** [comment]
Hi, I found this issue from two year's back, but before opening a new one wanted to report it here:

I see exactly the behavior described above by the initial issue creator, but changing the settings for `split_sentence` does not seem to make a difference. When using other translators, like the OpenAI one, the newlines stay, which is why I believe it has something to do with DeepL. Maybe it's on their end, but I'm not sure.

Any help is highly appreciated!
