### ISSUE TITLE
FastText restores settings at startup

### ISSUE THREAD

**Issue by andremeireles** [Fevol/obsidian-translate#39]
# User report

**Description:** After to install fastText language model, this plugin saves the plugins list setup **(which one is on or off)**, including the chosen theme and restores everything at obsidian startup.
So if you activate or deactivate plugins after activated this one, the changes will be "forgotten".
It's necessary activate obsidian-translate last if you want to avoid that.

# Reproducible Steps

1- Choose bergamot as the service
2- Install bergamot models
3- Install fastText

After that, whathever modifications will be discarded at restart.

# Temp Fix
Uninstall fastText or activate obsidian-translate last.

---
# Debugger data (do not alter)
**plugin_version**: "1.4.3"
**platform**: "Desktop"
**framework_version**: "0.15.6"
**obsidian_version**: "1.1.9"
**selected_service**: "bergamot"

**Comment by Fevol** [comment]
Many, many thanks for your detailed report! I had encountered this bug before, but I couldn't reproduce it. Your steps helped immensely with figuring out where the problem was located.

To make a long story short: when FastText is loaded during the initial app start-up (which happens when Bergamot & FastText are installed, or the glossary feature is enabled), there was an instruction that got executed, which made Obsidian think that all plugins were already loaded. 

I sincerely apologize for the trouble that this caused, I really should've caught this issue sooner. I'll try to get a new release out that fixes this issue ASAP.

**Comment by andremeireles** [comment]
It took me a while to reproduce the bug with other vaults, but when I did I was very happy because I was sure that such a good product would not be buggy for such a long time.
Thank you for being available so quickly and fixing the bug.
kudos for you.
