### ISSUE TITLE
[BUG] Issue with Fanyi Baidu

### ISSUE THREAD

**Issue by xxay-16** [Fevol/obsidian-translate#42]
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "Desktop"
**framework_version**: "1.1.9"
**obsidian_version**: "1.1.16"

**Comment by Fevol** [comment]
Thanks for the issue report @xxay-16!

Would you mind describing the bug you have with Fanyi Baidu for me? I don't have access to the service myself sadly, so to fix it, I need to know where exactly the issue is.

Many thanks in advance!

**Comment by Fevol** [comment]
If you're encountering an issue with Fanyi Baidu, please reply in this thread and give detailed information _how_/in what way the service does not work.

I cannot access the service myself, so your feedback would be much appreciated.

---

如果您在使用Fanyi Baidu时遇到问题，请在本主题中回复，并详细说明该服务是如何/以何种方式无法使用的。

我自己无法访问该服务，因此非常感谢您的反馈。

**Comment by solitary-sails** [comment]
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/e4e7764e-6d0c-41c5-9eb2-6e3f5082244b)
When trying to validate, an error is reported, and the content of the pop-up window is as follows.
I noticed that the error code corresponding to the error message is 52003, and in Baidu's develop doc, this means that "the appid is wrong or the service is not activated". However, I have tried to use the browser to directly access the api, and the results can be returned normally, so the service is activated. As for the appid, I think I did write it wrong. Please let me know if more information is required.

**Comment by Fevol** [comment]
> However, I have tried to use the browser to directly access the api, and the results can be returned normally, so the service is activated.

By that, do you mean that you can correctly call `https://fanyi-api.baidu.com/api/trans/vip/language?q=apple&salt=SALT&sign=MD5SIGN&appid=APPID`? 

I've been checking the code, everything looks correct, except maybe the salt generation. If I try their example request (with appid=`2015063000000001`, key=`12345678` and salt=`1435660288`), the request works without any problems.

If you don't mind, there are two things you could try:
1. Using a different way togenerate the salt
2. Changing the request type in the `service_validate` to do a translation instead of language recognition:
```ts
// Lines 71 - 77
const signature = await this.sign_message('apple');
const payload = {
	q: 'apple',
	appid: this.#app_id,
	salt: signature.salt,
	sign: signature.signature,
	from: 'en',
	to: 'zh',
}
```

**Comment by solitary-sails** [comment]
The end of URL should be "translate", not "language". What I called is `http://fanyi-api.baidu.com/api/trans/vip/translate?q=test&from=en&to=zh&appid=APPID&salt=SALT&sign=SIGN`.
If I just change "language" to "translate", reponse is 54000:PARAM_FROM_TO_OR_Q_EMPTY.I think it is because the param "from" and "to" is missed.They are also missed in validate function.

**Comment by solitary-sails** [comment]
Validation works well now.Btw, I also changed the Content-Type to "x-www-form-urlencoded" because that's what Baidu's documentation says. I'm not sure if this is necessary, but since it's working now, I think it's OK to keep it as it is.
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/9035fe3f-388c-4bef-a86b-f4f69cdcb449)

**Comment by Fevol** [comment]
That's fine! Will you be making a PR, or shall I push the changes?

If you don't mind, could you really quickly check whether language detection works properly too?
I think I made a small mistake with the url, it's very possible that the function will work again if you replace

https://github.com/Fevol/obsidian-translate/blob/d064f1b24c5a11b4ff792dff8812abbbdb9ac11c/src/handlers/fanyi-baidu.ts#L109

with:
```ts
url: `https://api.fanyi.baidu.com/api/trans/vip/language?` + new URLSearchParams(payload),
```

By the way, many thanks for helping with this! I really appreciate it.

**Comment by solitary-sails** [comment]
It's not the time yet, I just found out that there is still a little problem.
When I try to translate from English to Japanese, it works fine. But when I try to translate to Chinese, an error occurs, the content is:"580001:Target Language is not supported."
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/52f8e1b9-4860-47f3-af45-c679c6a7ec97)
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/c9106514-b94c-43e9-82c5-3beabd84dc23)

In addition, please tell me how to test the language detection function you mentioned.

**Comment by solitary-sails** [comment]
I think the reason is that Baidu's language code is different from ISO 639.
Here is the part of code that Baidu use:
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/603e4fa8-581d-42fb-ab9c-0389cf3f690c)

**Comment by Fevol** [comment]
It seems like I made a mistake with my language code mapping: function https://github.com/Fevol/obsidian-translate/blob/d064f1b24c5a11b4ff792dff8812abbbdb9ac11c/src/util.ts#L392-L792

Baidu uses a different ISO language code system, not quite [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3), and all other services use [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1), so I map these languages to the ISO-639-1 ones for convenience. It'll take me a bit to verify that all codes are correct.

---

> In addition, please tell me how to test the language detection function you mentioned.

You'll need to set `Fanyi Baidu` as your main translator in the settings:
![image](https://github.com/Fevol/obsidian-translate/assets/8179397/992c5538-be57-4d61-8c07-14690cc19fcc)

And then run the command `Translate: Detect Language of selection` while selecting text in the editor:
![image](https://github.com/Fevol/obsidian-translate/assets/8179397/f8f1b477-bafd-475f-9abc-e0ed939cf9f2)

**Comment by solitary-sails** [comment]
Language detection is not available, though I've got a little guess as to why. I'll test it later. It's late night here in China, I'm starting to lose my mind，I have to go to bed, sorry.

**Comment by Fevol** [comment]
No problem! Thank you again for all the help! I will push the correct ISO translation function soon, so the translation should work properly then.

Have a good night!

**Comment by solitary-sails** [comment]
I looked through Baidu's documentation, and I found that Baidu's language codes are basically based on ISO 639-2/B. 
However, on this basis, they replaced some commonly used languages with the codes in ISO 639-1. In addition, they also added some codes that are not included in the ISO standard, such as Chinese classical Chinese and Cantonese.
I will try to sort out these special language codes, but it will take some time. In this case, you can write a function like iso639_1to3 to process Baidu's language code.

**Comment by Fevol** [comment]
Ah thanks for figuring that out for me! I figured it was somewhat based on 639-2, so that's what I based myself off. Just be aware, I have already fixed most issues with the ISO 639-2 -> 639-1 translation in commit 881223c2331a3a83836db707dcdba57e5a877218. There's no need to do all that work again, because it gets quite tedious to verify that each one is correctly translated!

**Comment by solitary-sails** [comment]
🤔Well, I don't know much about TypeScript, maybe something is wrong with my understanding. I will test whether the modified util.ts works well later.

**Comment by Fevol** [comment]
I'll be heading off to bed soon. Just curious though, what is the current problem? Does the translator still fail to correctly translate Chinese, or is it the language detection?

**Comment by solitary-sails** [comment]
Both. Translator fail to translate Chinese, I noticed there is no language code for Chinese in iso639_atob function. Is you just missed it or you defined the mapping rule other place?
As for language detection, the error message is "54000:Required parameter is missing". I think it is caused by missing param in detect function just like validate function.
 After I added 'auto' as `from` and 'en' as `to`, it works, but result is ‘undefined'.
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/d65a7757-29ab-4c98-a48b-b9208837a276)
I think this is due to incorrect handling of the response.The relevant code is shown in the screenshot below, but I don't know much about  TypeScript, so I don't know how to adjust it. Maybe you will have some ideas for modification.The format of the response information is also provided with screenshots.
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/d4deffc3-3dee-42b8-a728-896d9657ee9e)
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/3b0278fc-593d-484d-a8ea-2e593a228c1f)

**Comment by Fevol** [comment]
> I noticed there is no language code for Chinese in iso639_atob function

I simplified the function to only map ISO639-2 languages that have a ISO639-1 counterpart. So, if you've picked regular Chinese, which uses `zh`, it should work properly. It might be possible that you've selected one of the Chinese dialects/writing systems, and that these haven't been mapped correctly.

Could you add a log line like `console.log(from, to)` inside the `service_translate()` function, just to see if I made a mistake there? 

Note that `chi` is not the language code they use in the developer documentation, `zh`  should work as-is:
https://github.com/solitary-sails/obsidian-translate/commit/56c7eee7a6d18e9081d51d831615cddd9b8f9c0b

![image](https://github.com/Fevol/obsidian-translate/assets/8179397/56eee177-6f7b-4698-9b5a-c92afa0bea4a)


---

I'm reasonably sure that you shouldn't have to add a destination/target language for language recognition.
The documentation is pretty clear which endpoint should be called for the task: [https://fanyi-api.baidu.com/doc/24](API docs), I think this should be replaced:
https://github.com/solitary-sails/obsidian-translate/blob/56c7eee7a6d18e9081d51d831615cddd9b8f9c0b/src/handlers/fanyi-baidu.ts#L113
```ts
url: `http://api.fanyi.baidu.com/api/trans/vip/language?` + new URLSearchParams(payload),
```

(Plus also remove these two lines again:)
https://github.com/solitary-sails/obsidian-translate/blob/56c7eee7a6d18e9081d51d831615cddd9b8f9c0b/src/handlers/fanyi-baidu.ts#L104C1-L105C13

**Comment by solitary-sails** [comment]
Baidu divides these APIs into different "services". Although they share the same identity for verification, they must be applied separately to use.
***
🤔It's really weird, it will be fine after this modification. I don't know if I accidentally copied the wrong version of the plugin to obsidian. Anyway it works fine now.I will re-create a fork to open a PR later.The current one is a real mess due to my edits😂

**Comment by Fevol** [comment]
@solitary-sails, if you have a little bit of time, could you check one last thing for me?
I've rewritten the baidu code a bit so that it checks whether you have access to the premium tier (and thus the extended set of languages). Normally, now when you validate, it will set it so that you will only be able to access/see the languages of your tier.

**Comment by solitary-sails** [comment]
Everything works fine, only supported languages are displayed.
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/474baa8f-4b72-48ca-b6a3-73f996a22712)

**Comment by solitary-sails** [comment]
But I have an additional suggestion, please wait a moment

**Comment by solitary-sails** [comment]
There is a feature called "Custom Terminology". Can you add a switch to control whether to pass the corresponding parameter?
![图片](https://github.com/Fevol/obsidian-translate/assets/52939914/dd2237a3-df60-4c0c-93c1-fd659a07f172)

**Comment by Fevol** [comment]
Done! Could you test if it works as expected?

You'll need to enable the `Apply glossary` setting under Functionality first:
![image](https://github.com/Fevol/obsidian-translate/assets/8179397/74f5f1a3-f009-46c9-8b73-8faab698dfe1)

**Comment by solitary-sails** [comment]
Only works in select mode. No change in translate view.🤔

**Comment by Fevol** [comment]
Oh yeah, that's because the setting only applies to commands, not to the translation view.
It'll probably get fixed if you open and close your translation view, but you can also set it via this:
![image](https://github.com/Fevol/obsidian-translate/assets/8179397/0e0ad2ac-0185-4392-92b1-f3706ac19f3d)

...it is a bit complicated, I'll admit. I'll need to sit down and try to see how I can make this a bit more clear

**Comment by solitary-sails** [comment]
Fine, it works now. But I think it's counter-intuitive rather than complicated.😂

**Comment by Fevol** [comment]
Alright, I've patched it a little bit for now. Clarified the language a little bit, and I did notice that a new translation view did not correctly copy over the global glossary setting. (There _is_ a method to the madness, but I won't bore you with the details 😄) 

Thank you so much for all the checking and fixing these past few days. I'm really thankful for all the help & advice. I'll be pushing the update now, hopefully I haven't forgotten any major issues.

(P.S.: Good luck with the Outer Wilds mod translations, I've actually been meaning to try those mods out myself!)
