### ISSUE TITLE
[BUG] Issue with Yandex Translate

### ISSUE THREAD

**Issue by dordenis** [Fevol/obsidian-translate#43]
# User report
**Description:** ADD A SHORT DESCRIPTION HERE 

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "Desktop"
**framework_version**: "1.1.9"
**obsidian_version**: "1.1.16"

**Comment by Fevol** [comment]
Thanks for the issue report @dordenis!

Would you mind describing the bug you have with Yandex translate for me? I don't have access to the service myself sadly, so to fix it, I need to know what exactly the issue is.

Many thanks in advance!

**Comment by Fevol** [comment]
If you're encountering an issue with Yandex Translate, please reply in this thread and give detailed information _how_/in what way the service does not work.

I cannot access the service myself, so your feedback would be much appreciated.

**Comment by xsa-dev** [comment]
I have some issue.
Я создал [сервисный аккаунт и создал API-KEY](https://cloud.yandex.com/en/docs/translate/) для того чтобы заполнить соответсвующее поле в плагине.
По нажатию на кнопку: TEST я получаю сообщение о том что API key is invalid.

Но этот сниппет работает нормально и токен одинаковый:
```python
import requests

IAM_TOKEN = 'AQVNyIxmg5_jhpkURtnqB3XJywZ6G5kXYFFnikbF'
target_language = 'ru'
texts = ["Hello", "World"]

body = {
    "targetLanguageCode": target_language,
    "texts": texts,
}

headers = {
    "Content-Type": "application/json",
    "Authorization": "Api-Key {0}".format(IAM_TOKEN)
}

response = requests.post('https://translate.api.cloud.yandex.net/translate/v2/translate',
    json = body,
    headers = headers
)

print(response.text)
```

Результат:

![image](https://github.com/Fevol/obsidian-translate/assets/16959353/7b2fe00f-d0be-4c43-a1f6-e14721cec327)

**Comment by Fevol** [comment]
Many thanks for the detailed explanation and example, this made it much easier to debug the issue.

It turns out, I was using an [older version](https://yandex.com/dev/translate/doc/dg/concepts/about.html) of the API, which doesn't seem to be supported anymore (or is just buggy)

I took the liberty to test out the API a bit with the key you provided, and verified that everything works as expected. (You should probably revoke it, just in case.)

The new version should be releasing soon!

---

Большое спасибо за подробное объяснение и пример, это значительно облегчило отладку проблемы.

Оказывается, я использовал [старую версию](https://yandex.com/dev/translate/doc/dg/concepts/about.html) API, которая, похоже, больше не поддерживается (или просто глючит).

Я взял на себя смелость немного протестировать API с помощью ключа, который вы предоставили, и убедился, что все работает так, как ожидалось. (Возможно, вам следует отозвать его, на всякий случай).

Новая версия должна выйти в ближайшее время!
