### ISSUE TITLE
[BUG] Plugin breaks "More options" menu

### ISSUE THREAD

**Issue by AntonTheDeveloper** [Fevol/obsidian-translate#45]
# User report

After installing this plugin and enabling it, I have got my "More options" menu broken. It doesn't scroll and has broken layout as long as the plugin is enabled. I have reproduced this bug on my usual vault and on newly created vault. 

Here screenshot and video https://github.com/AntonTheDeveloper/bug-reports/tree/37e850c48cc6684c7a46d6734007621038b21d0e/obsidian-translate

---
# Debugger data (do not alter)
**plugin_version**: "1.4.4"
**platform**: "Desktop"
**framework_version**: "1.1.16"
**obsidian_version**: "1.1.16"
**selected_service**: "google_translate"

**Comment by Fevol** [comment]
Many thanks for the detailed bug report! The issue was from an older bodge I used to add my own submenu's, since it wasn't natively supported (yet).

New solution uses the native submenu (supported from versions >1.0.0), I haven't tested if it works properly across all platforms yet, so an official release will have to be for later; currently I'm both working on a different plugin and s
everal other university projects. I'll definitely be coming back to this plugin to fix all the myriad API issues and implementing all feature requests. But that will be a little ways off.

In the meantime, I've attached the most recent build of the plugin (which includes the fix for this issue)
[Most recent build (as of 2023/04/04)](https://github.com/Fevol/obsidian-translate/files/11144307/translate.zip)
