### ISSUE TITLE
Please for the love of god do not monkeypatch String.format

### ISSUE THREAD

**Issue by necauqua** [Fevol/obsidian-translate#51]
You are making a plugin that runs in the same environment as code from other people, and doing something like [this](https://github.com/Fevol/obsidian-translate/blob/master/src/util.ts#L193) breaks `String.format` for everyone else. This should be obvious, but I guess it was not.

cc https://github.com/necauqua/obsidian-page-properties/issues/4

**Comment by Fevol** [comment]
Oh god, I really apologize for doing that, that is indeed incredibly stupid of me.  I'm putting out a fix ASAP.

The really dumb thing is that this is code I've written ages ago, and _never_ ended up using it. I added that back when I barely understood what prototypes would do.

I'm very sorry that you and the original issue creator had to go through all this debugging due to my poorly thought out code. All I can say is that I'll be taking a very good look at the entire codebase again, and try to remove any other potential problematic parts.

**Comment by necauqua** [comment]
Yeah sorry for the passive-agressive comment, I get over-excited really easily :)

**Comment by Fevol** [comment]
Closing this issue as the fix is shipped with public update [1.4.6](https://github.com/Fevol/obsidian-translate/releases/tag/1.4.6), apologies for the wait!
