### ISSUE TITLE
The translation service dropdown is empty

### ISSUE THREAD

**Issue by froses** [Fevol/obsidian-translate#55]
# User report
**Description:** The translation service dropdown is empty
The translation service dropdown menu is empty. And the unique service tab visible is "FastText Settings".

![TranslateSettings](https://github.com/Fevol/obsidian-translate/assets/8214985/5472553e-9cba-494e-b974-2314a3283e7a)

Thanks so much for your excellent work!

Francesc Rosés

---
# Debugger data (do not alter)
**plugin_version**: "1.4.6"
**platform**: "macOS"
**framework_version**: "1.3.7"
**obsidian_version**: "1.4.2"
**selected_service**: undefined

**Comment by froses** [comment]
If I reinstall the plugin, the issue is resolved. So, may be the problem is in the version upgrade.

Francesc Rosés

**Comment by Fevol** [comment]
Confirmed the bug, this is an oversight on my part introduced by these lines: https://github.com/Fevol/obsidian-translate/blob/7dc98136d3a31ae1c963d06be7745d4f3e508158/src/main.ts#L134-L136

The reason why that the services are not visisible, is because they're being 'filtered' away. If you reselect your desired services or , they will show again:
![image](https://github.com/Fevol/obsidian-translate/assets/8179397/1b494cdf-b216-4247-9cc9-4f160930ea6e)

I'll fix the issue in the release, I'm sorry for the confusion that this caused!
